language: python
sudo: false
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -U pip wheel coverage codecov
    - pip install -r requirements.txt py.test
    - python setup.py develop
script:
    - coverage run -m py.test -v tests/ && codecov
cache:
    directories:
        - $HOME/.cache/pip
